name: Build and Push Docker Image
on:
  push:
    branches: ["buildjet"]
jobs:
  docker:
    runs-on: buildjet-64vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: |
          lscpu
          curl ipinfo.io
          free -h
          df -h
