name: Build and Push Docker Image
on:
  push:
jobs:
  build:
    runs-on: macos-latest-xl
    container:
      image: diazaji/debian:kernel
    defaults:
      run:
        shell: bash --noprofile --norc -exo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
