name: Build and Push Docker Image
on:
  push:
jobs:
  build:
    runs-on: macos-latest-xl
    defaults:
      run:
        shell: bash --noprofile --norc -exo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Setup
        uses: docker-practice/actions-setup-docker@master
      - name: Run Docker
        run: |
          set -x
          docker run diazaji/debian:kernel lscpu
