on: [push]
jobs:
  setup-docker:
    runs-on: macos-latest-xl
    name: test
    steps:
      - name: Setup Docker
        uses: douglascamata/setup-docker-macos-action@main
      - name: Run Docker
        uses: docker://diazaji/debian:clang
      - name: test
        run: lscpu
