name: Build and Push Docker Image
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 6'
jobs:
  docker:
    strategy:
      matrix:
        image: [kernel, toolchain]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: "${{ secrets.DOCKER_LOGIN }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push
        uses: docker/build-push-action@v6.0.1
        with:
          context: .
          file: ${{ matrix.image }}.Dockerfile
          push: true
          tags: diazaji/ubuntu:${{ matrix.image }}
