name: Run macos runner
on:
  push:
    branches: [macos]
  workflow_dispatch:
jobs:
  docker:
    runs-on: macos-13-large
    steps:
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha.13
      - name: Build Docker image
        run: docker run --rm diazaji/debian:kernel /bin/bash -c 'lscpu; free -h; df -h;'