name: Build and Push Docker Image
on:
  push:
    branches:
      - test-github
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - uses: actions/checkout@v4
      - name: Install Packages
        shell: sudo bash --noprofile --norc -e -o pipefail {0}
        run: |
          apt-get update
          apt-get install -y linux-tools-common
          perf record -a -e cycles:u -b any,u -o /dev/null sleep 1
