name: Build and Push Docker Image
on:
  push:
    branches:
      - test-github
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: diazaji/debian:kernel
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - uses: actions/checkout@v4
      - name: Test
        run: |
          ls
          pwd
          df -h
          free -h
          lscpu
