name: Build and Push Docker Image
on:
  push:
    branches:
      - test-github
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          df -h
          free -h
          lscpu
