on: [push]
jobs:
  setup-docker:
    runs-on: macos-latest-xl
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker
        uses: douglascamata/setup-docker-macos-action@main
      - name: Run
        run: docker run --rm diazaji/debian:kernel ls
