on: [push]
jobs:
  setup-docker:
    runs-on: macos-latest-xl
    name: test
    steps:
      - name: Setup Docker
        uses: douglascamata/setup-docker-macos-action@main
      - name: Run Docker
        run: |
          docker run diazaji/debian:kernel \
          --volume $GITHUB_WORKSPACE:/workspace \
          --cpus $(sysctl -n hw.ncpu) \
          sh -c "lscpu;nproc;ls workspace"
