name: Build and Push Docker Image
on:
  push:
    branches:
      - test-github
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 10240
      - uses: actions/checkout@v4
      - name: Test
        run: |
          docker run --rm -v /home/runner/work/docker/docker:/root \
            -w /root -e GITHUB_TOKEN diazaji/debian:kernel /bin/bash -c \
            '
            apt update
            apt install free -y
            free -h
            df -h
            ls
            pwd
            '
